apiVersion: apps/v1
kind: Deployment
metadata:
  name: digibuild-logbook-ui-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: digibuild-logbook-ui
  template:
    metadata:
      labels:
        app: digibuild-logbook-ui
    spec:
      containers:
      - name: digibuild-logbook-ui-container
        image: giurbinati/digibuild:dbl-ui
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 2Gi
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: digibuild-logbook-ui-service
spec:
  selector:
    app: digibuild-logbook-ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer